<?php
$mainFgColor = '#000000';
$mainBgColor = '#FFFFFF';

$headerFgColor = $mainFgColor;
$headerBgColor = $mainBgColor;
$headerBordColor = $headerFgColor;

$linkFgColor = '#444444';
$alinkFgColor = '#000000';
$vlinkFgColor = '#222222';

$fieldsetBordColor = $headerBordColor;
$legendFgColor = '#666666';

$formElemFgColor = $mainFgColor;
$formElemBgColor = $mainBgColor;
$formElemFocusBgColor = '#F6F6F6';

$submitButtonFgColor = $mainFgColor;
$submitButtonBgColor = $mainBgColor;

$buttonLinksFgColor = $submitButtonFgColor;
$buttonLinksBgColor = $submitButtonBgColor;

$logoFgColor = $mainFgColor;
$logoBgColor = $mainBgColor;

$toolbarFgColor = $mainFgColor;
$toolbarBgColor = $mainBgColor;
$toolbarBordColor = $headerBordColor;

$navFgColor = $mainFgColor;
$navBgColor = $mainBgColor;
$navTitleFgColor = $logoBgColor;
$navTitleBgColor = $logoFgColor;
$navLinkFgColor = $mainFgColor;

$tocFgColor = $mainFgColor;
$tocBgColor = $mainBgColor;
$tocBordColor = $fieldsetBordColor;

$footerFgColor = $toolbarFgColor;
$footerBgColor = $toolbarBgColor;
$footerBordColor = $toolbarBordColor;

$readMarkFgColor = $mainFgColor;
$readMarkBgColor = 'inherit';

$codeFgColor = '#001100';
$codeBgColor = '#FCFCFC';
$codeBordColor = $headerBordColor;

$errorFgColor = '#110000';
$extraInfoFgColor = '#333333';
$insBgColor = '#F0FFF0';
$delBgColor = '#FFF0F0';

$oddFgColor = $mainFgColor;
$oddBgColor = $mainBgColor;
$evenFgColor = $mainFgColor;
$evenBgColor = '#F0F0F0';
