<?php
$mainFgColor = '#000000';
$mainBgColor = '#ECF1F5';

$headerFgColor = $mainFgColor;
$headerBgColor = '#82B5FF'; #4C4C4C table.content border
$headerBordColor = '#D8DCEE';

$linkFgColor = '#0000EE';
$alinkFgColor = '#EE0000';
$vlinkFgColor = '#551A8B';

$fieldsetBordColor = $headerBordColor;
$legendFgColor = '#D03030';

$formElemFgColor = $mainFgColor;
$formElemBgColor = $mainBgColor;
$formElemFocusBgColor = '#FFFFFF';

$submitButtonFgColor = $mainFgColor;
$submitButtonBgColor = $headerBgColor;

$buttonLinksFgColor = $submitButtonFgColor;
$buttonLinksBgColor = $submitButtonBgColor;

$logoFgColor = $headerBgColor;
$logoBgColor = $mainBgColor;
$logoFontWeight = 'bold';
$logoFontSize = '1.3em';

$toolbarFgColor = $mainFgColor;
$toolbarBgColor = $headerBgColor;
$toolbarBordColor = $headerBordColor;

$navFgColor = $mainFgColor;
$navBgColor = '#E6EEFA';
$navTitleFgColor = '#FFFFFF';
$navTitleBgColor = $logoFgColor; #D8DCEE - hr border, #navigation dl border
$navLinkFgColor = '#4C4C4C';

$tocFgColor = $mainFgColor;
$tocBgColor = '#F8F8FC';
$tocBordColor = $fieldsetBordColor;

$footerFgColor = $toolbarFgColor;
$footerBgColor = $toolbarBgColor;
$footerBordColor = $toolbarBordColor;

$readMarkFgColor = $mainFgColor;
$readMarkBgColor = 'inherit';

$codeFgColor = '#003300';
$codeBgColor = '#FCFCFC';
$codeBordColor = '#C0C0C0';

$errorFgColor = '#CC0000';
$extraInfoFgColor = '#333333';
$extLinkFgColor = '#006F4E';
$insBgColor = '#DDFFDD';
$delBgColor = '#FFCCCC';

$oddFgColor = '#4C4C4C';
$oddBgColor = '#F8F8FC';
$evenFgColor = $oddFgColor;
$evenBgColor = '#E6EEFA';
