<?php
$mainFgColor = '#FFFFFF';
$mainBgColor = '#060919';

$headerFgColor = $mainFgColor;
$headerBgColor = '#001470';
$headerBordColor = '#002EFF';

$linkFgColor = '#FFFF11';
$alinkFgColor = '#11FFFF';
$vlinkFgColor = '#AAE574';

$fieldsetBordColor = $headerBordColor;
$legendFgColor = '#2FCFCF';

$formElemFgColor = $mainFgColor;
$formElemBgColor = $mainBgColor;
$formElemFocusBgColor = '#000000';

$submitButtonFgColor = $mainFgColor;
$submitButtonBgColor = '#021292';

$buttonLinksFgColor = $submitButtonFgColor;
$buttonLinksBgColor = $submitButtonBgColor;

$logoFgColor = '#0055FF';
$logoBgColor = $mainBgColor;

$toolbarFgColor = $mainFgColor;
$toolbarBgColor = '#001160';
$toolbarBordColor = '#0025D0';

$navFgColor = $mainFgColor;
$navBgColor = $mainBgColor;
$navTitleFgColor = '#000000';
$navTitleBgColor = $logoFgColor;
$navLinkFgColor = '#80BAFF';

$tocFgColor = $mainFgColor;
$tocBgColor = '#00091C';
$tocBordColor = $fieldsetBordColor;

$footerFgColor = $toolbarFgColor;
$footerBgColor = $toolbarBgColor;
$footerBordColor = $toolbarBordColor;

$readMarkFgColor = $mainFgColor;
$readMarkBgColor = 'inherit';

$codeFgColor = '#FFCCFF';
$codeBgColor = '#030303';
$codeBordColor = '#3F3F3F';
$errorFgColor = '#33FFFF';
$extraInfoFgColor = '#CCCCCC';
$extLinkFgColor = '#FF90B1';
$insBgColor = '#440044';
$delBgColor = '#004444';

$oddFgColor = $mainFgColor;
$oddBgColor = $mainBgColor;
$evenFgColor = $mainFgColor;
$evenBgColor = '#021232';
