<?php
$mainFgColor = '#F0F0F0';
$mainBgColor = '#103821';

$headerFgColor = $mainFgColor;
$headerBgColor = '#0B2516';
$headerBordColor = '#2C8531';

$linkFgColor = '#94FFB9';
$alinkFgColor = '#FAFF5D';
$vlinkFgColor = '#DDFFC0';

$fieldsetBordColor = $headerBordColor;
$legendFgColor = '#48DB4F';

$formElemFgColor = $mainFgColor;
$formElemBgColor = $mainBgColor;
$formElemFocusBgColor = '#000000';

$submitButtonFgColor = $mainFgColor;
$submitButtonBgColor = '#1C623A';

$buttonLinksFgColor = $submitButtonFgColor;
$buttonLinksBgColor = $submitButtonBgColor;

$logoFgColor = $mainFgColor;
$logoBgColor = $mainBgColor;

$toolbarFgColor = $mainFgColor;
$toolbarBgColor = $headerBgColor;
$toolbarBordColor = $headerBordColor;

$navFgColor = $mainFgColor;
$navBgColor = '#144F14';
$navTitleFgColor = $headerFgColor;
$navTitleBgColor = $headerBgColor;
$navLinkFgColor = $mainFgColor;

$tocFgColor = $mainFgColor;
$tocBgColor = $navBgColor;
$tocBordColor = $fieldsetBordColor;

$footerFgColor = $toolbarFgColor;
$footerBgColor = $toolbarBgColor;
$footerBordColor = $toolbarBordColor;

$readMarkFgColor = $mainFgColor;
$readMarkBgColor = 'inherit';

$codeFgColor = '#003300';
$codeBgColor = '#FCFCFC';
$codeBordColor = '#C0C0C0';

$errorFgColor = '#CC0000';
$extraInfoFgColor = '#e0e0e0';
$insBgColor = '#DDFFDD';
$delBgColor = '#FFCCCC';

$oddFgColor = $mainFgColor;
$oddBgColor = $mainBgColor;
$evenFgColor = $mainFgColor;
$evenBgColor = $navBgColor;
