<?php
$mainFgColor = '#000000';
$mainBgColor = '#F9F6E6';#F9F3D9 FCF9E9

$headerFgColor = $mainFgColor;
$headerBgColor = '#FFEB8F';
$headerBordColor = '#FFD100';

$linkFgColor = '#0000EE';
$alinkFgColor = '#EE0000';
$vlinkFgColor = '#551A8B';

$fieldsetBordColor = $headerBordColor;
$legendFgColor = '#D03030';

$formElemFgColor = $mainFgColor;
$formElemBgColor = $mainBgColor;
$formElemFocusBgColor = '#FFFFFF';

$submitButtonFgColor = $mainFgColor;
$submitButtonBgColor = '#FDED6D';

$buttonLinksFgColor = $submitButtonFgColor;
$buttonLinksBgColor = $submitButtonBgColor;

$logoFgColor = '#FFAA00';
$logoBgColor = $mainBgColor;

$toolbarFgColor = $mainFgColor;
$toolbarBgColor = '#FFF096';
$toolbarBordColor = '#FFDA2F';

$navFgColor = $mainFgColor;
$navBgColor = $mainBgColor;
$navTitleFgColor = '#FFFFFF';
$navTitleBgColor = $logoFgColor;
$navLinkFgColor = '#7F4500';

$tocFgColor = $mainFgColor;
$tocBgColor = '#FFFCEF';
$tocBordColor = $fieldsetBordColor;

$footerFgColor = $toolbarFgColor;
$footerBgColor = $toolbarBgColor;
$footerBordColor = $toolbarBordColor;

$readMarkFgColor = $mainFgColor;
$readMarkBgColor = 'inherit';

$codeFgColor = '#003300';
$codeBgColor = '#FCFCFC';
$codeBordColor = '#C0C0C0';

$errorFgColor = '#CC0000';
$extraInfoFgColor = '#333333';
$extLinkFgColor = '#006F4E';
$insBgColor = '#DDFFDD';
$delBgColor = '#FFCCCC';

$oddFgColor = $mainFgColor;
$oddBgColor = $mainBgColor;
$evenFgColor = $mainFgColor;
$evenBgColor = '#FDEDCD';
