<?php
$mainFgColor = '#000000';
$mainBgColor = '#FFF9DC';

$headerFgColor = $mainFgColor;
$headerBgColor = '#D9D0E8';
$headerBordColor = '#C282D8';

$linkFgColor = '#0000EE';
$alinkFgColor = '#EE0000';
$vlinkFgColor = '#551A8B';

$fieldsetBordColor = $headerBordColor;
$legendFgColor = '#D03030';

$formElemFgColor = $mainFgColor;
$formElemBgColor = $mainBgColor;
$formElemFocusBgColor = '#FFFFFF';

$submitButtonFgColor = $mainFgColor;
$submitButtonBgColor = $headerBgColor;

$buttonLinksFgColor = $submitButtonFgColor;
$buttonLinksBgColor = $submitButtonBgColor;

$logoFgColor = $headerBordColor;
$logoBgColor = $mainBgColor;
$logoFontStyle = 'normal';
$logoFontWeight = 'bold';
$logoFontSize = '1.3em';

$navFgColor = $mainFgColor;
$navBgColor = '#FCF6F2';
$navTitleFgColor = '#39373D';
$navTitleBgColor = $headerBgColor;
$navLinkFgColor = '#252327';

$toolbarFgColor = $mainFgColor;
$toolbarBgColor = $navTitleBgColor;
$toolbarBordColor = $headerBordColor;

$tocFgColor = $mainFgColor;
$tocBgColor = '#FBF9F4';
$tocBordColor = $fieldsetBordColor;

$footerFgColor = $toolbarFgColor;
$footerBgColor = $toolbarBgColor;
$footerBordColor = $toolbarBordColor;

$readMarkFgColor = $mainFgColor;
$readMarkBgColor = 'inherit';

$codeFgColor = '#003300';
$codeBgColor = '#FCFCFC';
$codeBordColor = '#C0C0C0';

$errorFgColor = '#CC0000';
$extraInfoFgColor = '#333333';
$extLinkFgColor = '#006F4E';
$insBgColor = '#BBFFBB';
$delBgColor = '#FFBBBB';

$oddFgColor = '#252327';
$oddBgColor = $tocBgColor;
$evenFgColor = $oddFgColor;
$evenBgColor = '#ECE6F9';
?>
